# Detials
#
#

# Experiment setup
EXPERIMENT_NAME: test_1

# Dataset config
DATASET:
  # Training params
  TRAIN: ./data/jersey_dataset_v4/train
  TRAIN_JSON: /train.json
  TRAIN_TRANSFORMS: NULL

  # Validation params
  VAL: ./data/jersey_dataset_v4/val
  VAL_JSON: /val.json
  VAL_TRANSFORMS: NULL

  # Test params
  TEST: ./data/jersey_dataset_v4/test
  TEST_JSON: /test.json
  TEST_TRANSFORMS: NULL

# Dataloader condig
DATALOADER:
  # Loader train params
  TRAIN:
    BATCH_SIZE: 1
    SHUFFLE: TRUE
    WORKERS: 8
  
  # Loader validation params
  VAL:
    BATCH_SIZE: 1
    SHUFFLE: FALSE
    WORKERS: 8

  # Loader test params
  TEST:
    BATCH_SIZE: 1
    SHUFFLE: FALSE
    WORKERS: 8

# model config
MODEL:
  MODEL_NAME: Mask_RCNN
  BACKBONE_NAME: resnet_50
  TRAINED:
    FLAG: TRUE
    SS_FLAG: TRUE
    BACKBONE_ROOT: backbone_weights/best_model.pth 
  TRAINABLE_LAYERS: 5
  NUM_CLASSES: 2
  MIN: 800
  MAX: 1333


# optimizer and scheduler config
OPTIMIZER:
  NAME: Adam
  PARAMS:
    - 0.00005
SCHEDULER:
  NAME: StepLR
  PARAMS:
    - 2
    - 0.1

# loop config
LOOP:
  START_EPOCH: 0
  END_EPOCH: 10

# reporting config
REPORTING:
  PRINT_FREQ: 20
